export const SET_IMAGES = "SET_IMAGES";
export const SET_SEARCHED_IMAGES = "SET_SEARCHED_IMAGES";
export const RESET_SEARCHED_IMAGES = "RESET_SEARCHED_IMAGES";
export const SET_IMAGES_BY_ORIENTATION = "SET_iMAGES_BY_ORIENTATION";
export const RESET_IMAGES_BY_ORIENTATION = "RESET_IMAGES_BY_ORIENTATION";
