export const SET_IMAGES = "SET_IMAGES";
export const SET_SEARCHED_IMAGES = "SET_SEARCHED_IMAGES";
export const RESET_SEARCHED_IMAGES = "RESET_SEARCHED_IMAGES";
export const SET_IMAGES_BY_ORIENTATION = "SET_iMAGES_BY_ORIENTATION";
export const RESET_IMAGES_BY_ORIENTATION = "RESET_IMAGES_BY_ORIENTATION";
export const SET_IMAGES_BY_CATEGORY = "SET_IMAGES_BY_CATEGORY";
export const RESET_IMAGES_BY_CATEGORY = "RESET_IMAGES_BY_CATEGORY";

export const SET_IMAGES_BY_COLORS = "SET_IMAGES_BY_COLORS";
export const RESET_IMAGES_BY_COLORS = "RESET_IMAGES_BY_COLORS";
export const RESET_IMAGES_BY_TYPE = "RESET_IMAGES_BY_TYPE";
export const SET_IMAGES_BY_TYPE = "SET_IMAGES_BY_TYPE";
export const SET_ORIENTATION_TYPE = "SET_ORIENTATION_TYPE";
export const RESET_ORIENTATION_TYPE = "RESET_ORIENTATION_TYPE";
